{% macro local_name(node, index) -%}
{{ (index + 1) }} {{ node.nodeName | replace(',', '，') | replace('=', '-') | replace('\r', ' ') | replace('\n', ' ') | trim }}
{%- endmacro %}
# Generated by Surgio. Edit the templates instead of this output file.

[General]
skip-proxy = 127.0.0.1, localhost, *.local
dns-server = system
ipv6 = true
test-timeout = 5
loglevel = notify

[Proxy]
{% for node in nodeList -%}
{{ local_name(node, loop.index0) }} = socks5, 127.0.0.1, {{ customParams.singboxSocksBasePort + loop.index0 }}, udp-relay=true
{% endfor %}

[Proxy Group]
Bridge = select, DIRECT{% if nodeList | length > 0 %}, Auto{% for node in nodeList %}, {{ local_name(node, loop.index0) }}{% endfor %}{% endif %}
{% if nodeList | length > 0 -%}
Auto = url-test{% for node in nodeList %}, {{ local_name(node, loop.index0) }}{% endfor %}, url = {{ proxyTestUrl }}, interval = {{ proxyTestInterval }}, tolerance = 150
{% endif %}

[Rule]
FINAL,Bridge

